### ISSUE TITLE
Separate dev / test setup scripts from general provider setup

### ISSUE THREAD

**Issue by forgetso** [prosopo-io/provider#230]

**Comment by goastler** [comment]
cli has varius dev stuff 
tasks file has dev stuff (e.g. gen mnemonic)
tests imports various of the two above

Some / all of this should be pulled out into own section (like we do with the tests)

**Comment by goastler** [comment]
need to add a tsconfig.test and tesconfig.dev for including corresponding sections of the src code depending on your situation (e.g. dev'ing / testing / building)

Need corresponding npm scripts for this too

**Comment by forgetso** [comment]
This should be done as part of the separate dev package. `tsconfig.test.json` has been added in the meantime
