### ISSUE TITLE
make provider return a signed payload to the user reflecting their approval

### ISSUE THREAD

**Issue by goastler** [prosopo-io/provider#253]

**Comment by goastler** [comment]
So this was a _fun_ problem! `ink` provides `ecdsa_recover()` to check an ecdsa signature against a given payload and public key (i.e. account id), returning true/false for whether the signature is valid.

However, polkadot js extension stores the user key pairs (public + private key) and does not allow users of the extension to access anything but the public key (rightly so, as it shouldn't be distributing private keys out!). The extension stores these accounts in a keyring, and the keyring controls what format those accounts take. By format, I mean encryption type: ecdsa, ed25519, sr25519 and ethereum (a compat type I believe). The extension does not provide functionality to use anything other than sr25519 for the account operations, so the signing produces a sr25519 signature. This signature is incompatible with ecdsa.

Therefore there's two options:
1. make a change to polkjs extension to allow keyring to be in different formats, PR that in and get a new release issued. Obviously this is quite the mountain to climb!
2. make ink support sr25519 verification instead of ecdsa (less of a mountain to climb)

**Comment by goastler** [comment]
I've gone through exactly what polkjs apps does when signing/verifying. I've found it uses a wasm under the hood for doing the signing / verification for ed25519 (edward), ecdsa and sr25519 (schnorrkel). The wasm uses a rust crate called schnorrkel which can be imported into the contract.

I've done that and can successfully verify signatures in sr25519 format, with a minor caveat below:

for some reason, the payload is wrapped before signing in polkjs apps. This is why the signature process was not lining up on polkjs apps and rust for so long, because the payloads were different! The payload gets wrapped in a Byte tag, e.g.

in polk js apps, the following strings map to these hexes:
`hello` -> `0x3c42797465733e68656c6c6f3c2f42797465733e`
`<Byte>hello</Byte>` -> `3c42797465733e68656c6c6f3c2f42797465733e`

All payloads are checked for the wrapping `Byte` tag and if not present, it is added, then converted to hex, hence the above two payloads producing the same string.

**Comment by goastler** [comment]
payloads of different lengths don't play well with rust so we'll just take the blake 256 hash of the payload and use that as the payload. This makes the payload much lighter for communication and makes it fixed size for the contract parameters

**Comment by goastler** [comment]
how much does adding the schnorrkel crate bloat the contract? 95.6KB -> 123.6KB

**Comment by forgetso** [comment]
Superseded by weighting providers
